author = "Hyaena Technologies"
description = "Synchronize GitHub Forks"
license = "AGPL-3.0"
name = "gh_sync"
version = "1.0.0"

[build]
auto-executables = false
auto-examples = false
auto-tests = false

[[executable]]
name = "gh-sync"
source-dir = "src"
main = "main.f90"

[fortran]
implicit-external = false
implicit-typing = false
source-form = "free"

[install]
library = false

